version: "3.9"

services:
  app:
    build: .
    container_name: postass_app
    ports:
      - "8080:80"
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
    volumes:
      - ./:/var/www/html:delegated
      - ./assets:/var/www/html/public/assets:ro
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: postass_db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=postass
      - MYSQL_USER=postass
      - MYSQL_PASSWORD=postass
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "33060:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:5
    container_name: postass_pma
    restart: unless-stopped
    environment:
      - PMA_HOST=db
      - PMA_USER=postass
      - PMA_PASSWORD=postass
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  db_data:


